name: food-shocks
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.13.3
  - numpy=2.2.6
  - pandas=2.2.3
  - matplotlib=3.10.3
  - requests=2.32.3
  - tqdm=4.67.1
  - pytest=8.3.5
  - scipy=1.15.2
  - seaborn=0.13.2
  - geopandas=1.0.1
  - country_converter=1.2
  - fiona=1.10.1
